labels:
  # -- L of LPSD of Gotrade Service Tree
  landscape: develop
  # -- P of LPSD of Gotrade Service Tree
  platform: systems
  # -- P of LPSD of Gotrade Service Tree
  service: db-ui
  # -- Infrastructure layer this application belongs to
  layer: "2"
  # -- Team in charge of this chart
  team: ESD
pgweb:
  enable: true
  ingress:
    enable: false
  designation: pgweb
  service:
    type: ClusterIP
    port: 80
  image:
    repository: ghcr.io/sosedoff/pgweb
    tag: 0.14.0
    pullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1m
      memory: 32Mi
  nodeSelector:
    kubernetes.io/os: linux
cloudbeaver:
  enable: false
  ingress:
    enable: false
  storage:
    class: local-path
    size: 512Mi
  designation: cloudbeaver
  service:
    type: ClusterIP
    port: 80
  image:
    repository: dbeaver/cloudbeaver
    tag: 22.3.5
    pullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  nodeSelector:
    kubernetes.io/os: linux
adminer:
  designation: adminer
  enable: true
  ingress:
    enable: false
  service:
    type: ClusterIP
    port: 80
  image:
    repository: adminer
    tag: 4.8.1
    pullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1m
      memory: 256Mi
  nodeSelector:
      kubernetes.io/os: linux

commander:
  designation: commander
  enable: false
  ingress:
    enable: false
  service:
    type: ClusterIP
    port: 80
  image:
    repository: ghcr.io/joeferner/redis-commander
    tag: 0.8.1
    pullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  nodeSelector:
      kubernetes.io/os: linux
