apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-{{ .Values.appVersion }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        {{ .Values.key }}: {{ .Values.value }}

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
