{{ if .Values.commander.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotrade-db-ui.fullname" . }}-{{ .Values.commander.designation }}
  labels:
    {{- include "gotrade-db-ui.labels" . | nindent 4 }}
    {{- include "gotrade-db-ui.tr8labels" . | nindent 4 }}
    tr8.io/designation: "{{ .Values.commander.designation }}"
  annotations:
    {{- include "gotrade-db-ui.tr8labels" . | nindent 4 }}
    tr8.io/designation: "{{ .Values.commander.designation }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gotrade-db-ui.labels" . | nindent 6 }}
      {{- include "gotrade-db-ui.tr8labels" . | nindent 6 }}
      tr8.io/designation: "{{ .Values.commander.designation }}"
  template:
    metadata:
      labels:
        {{- include "gotrade-db-ui.labels" . | nindent 8 }}
        {{- include "gotrade-db-ui.tr8labels" . | nindent 8 }}
        tr8.io/designation: "{{ .Values.commander.designation }}"
      annotations:
        {{- include "gotrade-db-ui.tr8labels" . | nindent 8 }}
        tr8.io/designation: "{{ .Values.commander.designation }}"
    spec:
      securityContext:
      {{- toYaml .Values.commander.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.commander.designation }}
          securityContext:
          {{- toYaml .Values.commander.securityContext | nindent 12 }}
          image: "{{ .Values.commander.image.repository }}:{{ .Values.commander.image.tag }}"
          imagePullPolicy: {{ .Values.commander.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      {{- toYaml .Values.commander.resources | nindent 12 }}
      {{- with .Values.commander.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commander.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commander.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
