{{ if .Values.cloudbeaver.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotrade-db-ui.fullname" . }}-{{ .Values.cloudbeaver.designation }}
  labels:
    {{- include "gotrade-db-ui.labels" . | nindent 4 }}
    {{- include "gotrade-db-ui.tr8labels" . | nindent 4 }}
    tr8.io/designation: {{ .Values.cloudbeaver.designation }}
spec:
  type: {{ .Values.cloudbeaver.service.type }}
  ports:
    - port: {{ .Values.cloudbeaver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gotrade-db-ui.labels" . | nindent 4 }}
    {{- include "gotrade-db-ui.tr8labels" . | nindent 4 }}
    tr8.io/designation: {{ .Values.cloudbeaver.designation }}
{{- end }}
